---
name: "Awards Metadata"
guid: "38895a18-37d8-4a0a-92f8-c38335820627"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Apply custom award metadata tags"
description: >
  Adds custom award metadata tags to media items in Jellyfin.
category: "Metadata"
owner: "scott.fridlund"
artifacts:
  - "Jellyfin.Plugin.AwardsMetadata.dll"
changelog: >
  1.0.0.0: Initial release